課題完了
kzri4/Suica pull request #1
Opened 2021-02-23 11:19 UTC by kzri4

課題が完了しましたので、ご確認お願い致します。

2021-02-23 12:25 UTC, kazu-taka requested changes
@kzri4 
いくつかコメントしたので修正お願いします✨
インデントとかきっちりしているので、前より綺麗なコードになりましたね👍

2021-02-23 12:25 UTC, kazu-taka commented on index.php
> +$selects = array("1:" => 1000 ,"2:" => 3000 ,"3:" => 5000);
@kzri4 
連想配列の場合`["1" => 1000, "2" => 3000, "3" => 5000]`の方が分かりやすいので、echoするタイミングで`:`を付加してた方がいいかなと思います✨
`:`はそこでしか使用しないので！
また、最近のPHPの書き方では連想配列や配列を定義する時は、`array`より`[]`を使うほうが一般的なので、`[]`で書くようにお願いします😊

2021-02-23 12:25 UTC, kazu-taka commented on index.php
> +}
@kzri4 
ifやelseifで判定しているのは全て`$num`なので、その場合はswitchを使った方が良いです✨
また、1、2、3以外の時も後続の処理が実行されてしまうので、`echo "無効な番号です。処理を終了します。";`の直後に、プログラムを終了するように1文追加お願いします！

2021-02-23 12:25 UTC, kazu-taka commented on index.php
> +}
@kzri4 
フローチャートのループの部分で、買い物フラグを使用して判定しているので、フローチャートに合わせて、フラグを使用するように修正お願いします✨
特に仕様が決まっていない時であれば、残高を判定してループをするのは問題ないです👍
![スクリーンショット 2021-02-23 21 14 30](https://user-images.githubusercontent.com/5278718/108842136-29f4c100-761c-11eb-9a4f-3223aec14c13.png)
👍

2021-02-23 12:25 UTC, kazu-taka commented on index.php
> +$price = fgets(STDIN);
@kzri4 
ここで商品の価格は入力させず、while内の最初に価格を入力させるようにして下さい！
そちらもフローチャートを確認しながら修正お願いします🙏

2021-02-23 12:25 UTC, kazu-taka commented on index.php
> +while ($price <= $money ){
@kzri4 
ちなみにwhile以外にdo whileもあるので、最低1回は何か処理したい場合は、do whileを使ってみて下さい👍

2021-02-24 00:02 UTC, kazu-taka requested changes
@kzri4 
いくつかコメントしたので確認お願いします🙏

2021-02-24 00:02 UTC, kazu-taka commented on index.php
> +}
@kzri4 
ここで$shopping_flagを設定して、無効な番号かどうか判断していますが、そもそも1、2、3以外は無効なので、switchのdefaultのところに該当したものが全て無効になります！
ですので、defaultのところに
```php
    echo "無効な番号です" . PHP_EOL . "処理を終了します。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
    exit;
```
を入れることで、上記のコードは`$shopping_flag = true;`だけで良くなります✨
また、"true"は文字列のtrueになるので、真偽値のtrue、falseで扱いたい時は、`"`や`'`で囲わないようにして下さい👍

以降のところでも"true"や"false"としていて扱っているところがあったら、true、falseに修正お願いします😊

2021-02-24 00:02 UTC, kazu-taka commented on index.php
> +        break;
@kzri4
ここの部分は入力された番号をそのまま連想配列のキーとして使えると思うので、以下のようにリファクタリングするのもいいと思います✨
以下で動かなかったら`[1 => 1000 ,2 => 3000 ,3 => 5000]`に変更してみて下さい！
 
```php
    case 1:
    case 2:
    case 3: 
        $money = $selects[$num];
        echo $money . $messge;
        break;
```

2021-02-24 00:02 UTC, kazu-taka commented on index.php
> +
@kzri4 
ここは空行削除してOKです✨

2021-02-24 00:02 UTC, kazu-taka commented on index.php
> +        $rem = ($money - $price);
@kzri4 
ここの`()`は無くても良いです✨

2021-02-24 03:20 UTC, kzri4 reviewed
@kazu-taka
以下の様に2パターンで修正し、実行しましたが、
うまく連想配列から取り出しが出来ません。

```var_dump($num);```で中身を確認する限り、
```fgets(STDIN)```で入力された値は文字列になるようなので
```
$selects = ["1" => 1000, "2" => 3000, "3" => 5000];
```
で問題はないかと考えたのですが、
```var_dump($selects[$num]);```
で中身を確認したところ、```NULL```になってしまい
原因が不明です。


```
echo "Suicaにチャージします。金額に該当する番号を入力して下さい。" . PHP_EOL;

$selects = ["1" => 1000, "2" => 3000, "3" => 5000];

foreach ($selects as $select_num => $select_money) {
    echo $select_num . ":" . $select_money . "円" . PHP_EOL;
}

echo "番号:";
$num = fgets(STDIN);
$messge = "円チャージしました。" . PHP_EOL;

switch ($num) {
    case 1:
    case 2:
    case 3: 
        $money = $selects[$num];
        var_dump($num);
        var_dump($selects[$num]);
        echo $money . $messge;
        break;
    default:
        echo "無効な番号です" . PHP_EOL . "処理を終了します。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
        exit;    
}

```

```
KondonoMBP:shopping kondokazuma$ docker-compose exec app php php_exercise/shopping/index.php
Suicaにチャージします。金額に該当する番号を入力して下さい。
1:1000円
2:3000円
3:5000円
番号:1
string(2) "1
"
NULL
円チャージしました。
商品の価格を入力して下さい:
```


```

echo "Suicaにチャージします。金額に該当する番号を入力して下さい。" . PHP_EOL;

$selects = [1 => 1000, 2 => 3000, 3 => 5000];

foreach ($selects as $select_num => $select_money) {
    echo $select_num . ":" . $select_money . "円" . PHP_EOL;
}

echo "番号:";
$num = fgets(STDIN);
$messge = "円チャージしました。" . PHP_EOL;

switch ($num) {
    case 1:
    case 2:
    case 3: 
        $money = $selects[$num];
        var_dump($num);
        var_dump($selects[$num]);
        echo $money . $messge;
        break;
    default:
        echo "無効な番号です" . PHP_EOL . "処理を終了します。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
        exit;    
}
```

```
ondonoMBP:shopping kondokazuma$ docker-compose exec app php php_exercise/shopping/index.php
Suicaにチャージします。金額に該当する番号を入力して下さい。
1:1000円
2:3000円
3:5000円
番号:1
string(2) "1
"
NULL
円チャージしました。
商品の価格を入力して下さい:
```

2021-02-24 03:20 UTC, zeeero4 commented on index.php
> +        break;
@kazu-taka
以下の様に2パターンで修正し、実行しましたが、
うまく連想配列から取り出しが出来ません。

```var_dump($num);```で中身を確認する限り、
```fgets(STDIN)```で入力された値は文字列になるようなので
```
$selects = ["1" => 1000, "2" => 3000, "3" => 5000];
```
で問題はないかと考えたのですが、
```var_dump($selects[$num]);```
で中身を確認したところ、```NULL```になってしまい
原因が不明です。


```
echo "Suicaにチャージします。金額に該当する番号を入力して下さい。" . PHP_EOL;

$selects = ["1" => 1000, "2" => 3000, "3" => 5000];

foreach ($selects as $select_num => $select_money) {
    echo $select_num . ":" . $select_money . "円" . PHP_EOL;
}

echo "番号:";
$num = fgets(STDIN);
$messge = "円チャージしました。" . PHP_EOL;

switch ($num) {
    case 1:
    case 2:
    case 3: 
        $money = $selects[$num];
        var_dump($num);
        var_dump($selects[$num]);
        echo $money . $messge;
        break;
    default:
        echo "無効な番号です" . PHP_EOL . "処理を終了します。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
        exit;    
}

```

```
KondonoMBP:shopping kondokazuma$ docker-compose exec app php php_exercise/shopping/index.php
Suicaにチャージします。金額に該当する番号を入力して下さい。
1:1000円
2:3000円
3:5000円
番号:1
string(2) "1
"
NULL
円チャージしました。
商品の価格を入力して下さい:
```


```

echo "Suicaにチャージします。金額に該当する番号を入力して下さい。" . PHP_EOL;

$selects = [1 => 1000, 2 => 3000, 3 => 5000];

foreach ($selects as $select_num => $select_money) {
    echo $select_num . ":" . $select_money . "円" . PHP_EOL;
}

echo "番号:";
$num = fgets(STDIN);
$messge = "円チャージしました。" . PHP_EOL;

switch ($num) {
    case 1:
    case 2:
    case 3: 
        $money = $selects[$num];
        var_dump($num);
        var_dump($selects[$num]);
        echo $money . $messge;
        break;
    default:
        echo "無効な番号です" . PHP_EOL . "処理を終了します。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;
        exit;    
}
```

```
ondonoMBP:shopping kondokazuma$ docker-compose exec app php php_exercise/shopping/index.php
Suicaにチャージします。金額に該当する番号を入力して下さい。
1:1000円
2:3000円
3:5000円
番号:1
string(2) "1
"
NULL
円チャージしました。
商品の価格を入力して下さい:
```

2021-02-24 03:27 UTC, kazu-taka commented on index.php
> +        break;
@kzri4 
原因が分かりました！
ちゃんと検証せずコメントしてしてまってすみません🙏
```php
string(2) "1
"
```
上記を見てもらうと分かるかと思いますが、1の後に改行が入ってしまっているので、`"`が下の行に改行されてしまっています。
そこでうまく連想配列から値が取れなくなっていると思われます✨
[ここのサイト](https://sawatan.com/php/php%E3%81%A7%E6%A8%99%E6%BA%96%E5%85%A5%E5%8A%9B%E3%81%8B%E3%82%89%E6%94%B9%E8%A1%8C%E3%82%92%E5%8F%96%E3%82%8A%E9%99%A4%E3%81%8F%E3%81%AE%E3%81%AF%E3%80%81trim%E3%81%A7%E5%8D%81%E5%88%86%E3%81%A0)を参考に、`trim(fgets(STDIN))をしてもらうと、多分正常に動くようになると思われます！
動かない時はまた連絡下さい😂

2021-02-24 05:56 UTC, kazu-taka requested changes
@kzri4 
何点かコメントしたので確認お願いします😊

2021-02-24 05:56 UTC, kazu-taka commented on index.php
> +}
@kzri4 
ここの部分の修正漏れがあったので修正お願いします🙏
ここの時点で$moneyに何もセットされない事はないので(switchで正しく制御しているため)、ifで判定せず、`$shopping_flag = true`でOKです🙆‍♂️

2021-02-24 05:56 UTC, kazu-taka commented on index.php
> +} while ($rem >= 0);
@kzri4 
https://github.com/kzri4/Suica/pull/1#discussion_r580987834
ループの修正の部分も修正漏れですので、フラグで判断するように修正お願いします🙏

2021-02-24 05:56 UTC, kazu-taka commented on index.php
> +}
@kzri4 
すみません！前回の指摘漏れです！！
ループを抜けた時点で`$shopping_flag`は確実にfalseになっている想定なので、`echo "チャージ金額を上回るため購入できません。" . PHP_EOL . "買い物を終了します。" . PHP_EOL;`だけでOKです🙆‍♂️

2021-02-24 05:56 UTC, kazu-taka commented on index.php
> +    }
@kzri4 
こちらも前回の指摘漏れです^^;
$moneyにチャージ金額が設定されているので、$remを新たに作らず、$money - $priceを実行して残高を保持していく形でOKです！
上記の処理は以下の行のように短く事が可能です😊

```php
if ($money - $price >= 0) {
    // チャージ金額減らす処理
} else {
    // 買い物フラグをfalseに更新
}
```
ループの終了判定を`while (shopping_flag == false);`にしてもらえれば、途中でbreakしなくてもOKです！
😊

2021-02-24 06:31 UTC, kzri4 commented on index.php
> +    }
@kazu-taka
ありがとうございます。
```while (shopping_flag == false);```は、```while ($shopping_flag == true);```の間違いですかね^^;

2021-02-24 06:35 UTC, kazu-taka commented
@kzri4 
めちゃくちゃバッチリじゃないですか！！！
途中うまくいかない時に、var_dump使ってデバッグしてたあたりは本気で感動しました✨
いい感じにレベルアップしてます👍
マージしてOKです！！
![LGTM](https://image.lgtmoon.dev/117430)

2021-02-24 06:42 UTC, merged